import "./globals.css";
import Nav from "../components/Nav";
import Footer from "../components/Footer";
import { Roboto } from "next/font/google";
import QueryWrapper from "@/components/QueryWraper";
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  style: ["normal", "italic"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <QueryWrapper>
        <body className={`${roboto.className}`}>
          <div className="main-container">
            <Nav></Nav>
            <main className="col-start-2">{children}</main>
            <Footer></Footer>
          </div>
        </body>
      </QueryWrapper>
    </html>
  );
}
